services:
  # Backend API service
  api:
    build:
      context: .
    # command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload", "--log-level", "debug"]
      dockerfile: Dockerfile
    volumes:
      - .:/backend/
      - ./docker/.bash_history:/home/lifted/.bash_history
      - ./docker/.bash_aliases:/home/lifted/.bash_aliases
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    # TODO: Unsure if I need this outside of the VSCode container.
    # depends_on:
    #   - db

  # Database service
  db:
    image: postgres:latest
    container_name: deadlock_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    # Uncomment the following lines to persist data locally (not in container)
    # and to initialize the database with a SQL script.
    # If you have an init.sql file, you can mount it to initialize the database.
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - ./docker/db/:/docker-entrypoint-initdb.d/
    #   - ${PWD}/db_data:/var/lib/postgresql/data
    #   - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
